server:
  port: 8080
  timeoutSeconds: 30

database:
  host: postgres
  port: 5432
  user: postgres
  password: postgres
  name: aiclinic
  sslmode: disable

jwt:
  secret: "your-256-bit-secret"
  refresh_secret: "your-refresh-secret"
  expiry_hours: 24
  refresh_expiry_hours: 168

redis:
  url: "redis://localhost:6379/0"

event_tracking:
  enabled: true
  endpoints:
    patient:
      create:
        enabled: true
        event_type: "PATIENT_CREATED"
        tracked_fields:
          - name
          - email
          - status
          - dob
          - phone
          - address
      update:
        enabled: true
        event_type: "PATIENT_UPDATED"
        track_changes: true
        tracked_fields:
          - name
          - email
          - status
          - dob
          - phone
      delete:
        enabled: true
        event_type: "PATIENT_DELETED"
        tracked_fields:
          - id
    appointment:
      create:
        enabled: true
        event_type: "APPOINTMENT_CREATED"
        tracked_fields:
          - patient_id
          - clinician_id
          - start_time
          - end_time
      update:
        enabled: true
        event_type: "APPOINTMENT_UPDATED"
        track_changes: true
        tracked_fields:
          - start_time
          - end_time
          - status
      delete:
        enabled: true
        event_type: "APPOINTMENT_DELETED"
        tracked_fields:
          - id
    clinician:
      create:
        enabled: true
        event_type: "CLINICIAN_CREATED"
        tracked_fields:
          - name
          - email
          - role
      update:
        enabled: true
        event_type: "CLINICIAN_UPDATED"
        track_changes: true
        tracked_fields:
          - name
          - email
          - role
          - status
      delete:
        enabled: true
        event_type: "CLINICIAN_DELETED"
        tracked_fields:
          - id
    clinic:
      create:
        enabled: true
        event_type: "CLINIC_CREATED"
        tracked_fields:
          - name
          - address
          - contact
      update:
        enabled: true
        event_type: "CLINIC_UPDATED"
        track_changes: true
        tracked_fields:
          - name
          - address
          - contact
          - status
      delete:
        enabled: true
        event_type: "CLINIC_DELETED"
        tracked_fields:
          - id
    clinician_role:
      create:
        enabled: true
        event_type: "CLINICIAN_ROLE_ASSIGNED"
        tracked_fields:
          - clinician_id
          - role_id
          - organization_id
      delete:
        enabled: true
        event_type: "CLINICIAN_ROLE_REMOVED"
        tracked_fields:
          - clinician_id
          - role_id
    clinician_clinic:
      create:
        enabled: true
        event_type: "CLINICIAN_CLINIC_ASSIGNED"
        tracked_fields:
          - clinician_id
          - clinic_id
      delete:
        enabled: true
        event_type: "CLINICIAN_CLINIC_REMOVED"
        tracked_fields:
          - clinician_id
          - clinic_id
    organization:
      create:
        enabled: true
        event_type: "ORGANIZATION_CREATED"
        tracked_fields:
          - name
          - status
          - contact_email
          - contact_phone
      update:
        enabled: true
        event_type: "ORGANIZATION_UPDATED"
        track_changes: true
        tracked_fields:
          - name
          - status
          - contact_email
          - contact_phone
      delete:
        enabled: true
        event_type: "ORGANIZATION_DELETED"
        tracked_fields:
          - id
    rbac:
      role_create:
        enabled: true
        event_type: "ROLE_CREATED"
        tracked_fields:
          - name
          - description
          - organization_id
      role_update:
        enabled: true
        event_type: "ROLE_UPDATED"
        track_changes: true
        tracked_fields:
          - name
          - description
          - status
      role_delete:
        enabled: true
        event_type: "ROLE_DELETED"
        tracked_fields:
          - id
      permission_assign:
        enabled: true
        event_type: "PERMISSION_ASSIGNED"
        tracked_fields:
          - role_id
          - permission_id
      permission_remove:
        enabled: true
        event_type: "PERMISSION_REMOVED"
        tracked_fields:
          - role_id
          - permission_id
    permission:
      create:
        enabled: true
        event_type: "PERMISSION_CREATED"
        tracked_fields:
          - name
          - description
          - resource
          - action
      update:
        enabled: true
        event_type: "PERMISSION_UPDATED"
        track_changes: true
        tracked_fields:
          - name
          - description
          - resource
          - action
      delete:
        enabled: true
        event_type: "PERMISSION_DELETED"
        tracked_fields:
          - id 