database:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  name: admin_db
  sslmode: disable

redis:
  url: redis://localhost:6379
  max_retries: 3
  pool_size: 10
  min_idle_conns: 5

worker:
  outbox:
    batch_size: 100
    poll_interval: 5s
    retry_attempts: 3
    retry_delay: 10s 